services:
    traefik:
        image: traefik:3.6
        command:
            --providers.docker=true
            --providers.docker.exposedByDefault=false
            --entryPoints.http.address=:80
        ports:
            - "80:80"
        networks:
            - traefik-public
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
        labels:
            - traefik.enable=true
            - traefik.docker.network=traefik-public

    frontend:
        build:
            context: frontend/docker/development/nginx
        networks:
            - traefik-public
            - default
        labels:
            - traefik.enable=true
            - traefik.docker.network=traefik-public
            - traefik.http.routers.frontend.rule=Host(`localhost`) || Host(`www.localhost`)
            - traefik.http.routers.frontend.entryPoints=http
            - traefik.http.services.frontend.loadBalancer.server.port=80
            - traefik.http.middlewares.frontend-redirect.redirectRegex.regex=^(https?://)www\.localhost/(.*)$$
            - traefik.http.middlewares.frontend-redirect.redirectRegex.replacement=$${1}localhost/$${2}
            - traefik.http.middlewares.frontend-redirect.redirectRegex.permanent=true
            - traefik.http.routers.frontend.middlewares=frontend-redirect

    frontend-node:
        build:
            context: frontend/docker/development/node
            args:
                GID: ${GID:-1000}
                UID: ${UID:-1000}
        environment:
            VITE_AUTH_URL: http://api.localhost
        volumes:
            - ./frontend:/app
        command: ["sh", "-c", "until [ -f .ready ] ; do sleep 1 ; done && exec yarn start"]

    frontend-node-cli:
        build:
            context: frontend/docker/development/node
            args:
                GID: ${GID:-1000}
                UID: ${UID:-1000}
        environment:
            VITE_AUTH_URL: http://api.localhost
        volumes:
            - ./frontend:/app

    api:
        build:
            context: api/docker
            dockerfile: development/nginx/Dockerfile
        volumes:
            - ./api:/app
        networks:
            - traefik-public
            - default
        labels:
            - traefik.enable=true
            - traefik.docker.network=traefik-public
            - traefik.http.routers.api.rule=Host(`api.localhost`)
            - traefik.http.routers.api.entryPoints=http
            - traefik.http.services.api.loadBalancer.server.port=80

    api-php-fpm:
        build:
            context: api/docker
            dockerfile: development/php-fpm/Dockerfile
            args:
                GID: ${GID:-1000}
                UID: ${UID:-1000}
        environment:
            APP_ENV: dev
            APP_DEBUG: 1
            PHP_IDE_CONFIG: serverName=API
            DB_HOST: api-postgres
            DB_USER: app
            DB_PASSWORD: secret
            DB_NAME: app
            MAILER_HOST: mailer
            MAILER_PORT: 1025
            MAILER_USERNAME: app
            MAILER_PASSWORD: secret
            MAILER_FROM_EMAIL: mail@app.test
            FRONTEND_URL: http://localhost
            SENTRY_DSN: ""
            JWT_ENCRYPTION_KEY: secret
            JWT_PUBLIC_KEY_PATH: /run/secrets/jwt_public_key
            JWT_PRIVATE_KEY_PATH: /run/secrets/jwt_private_key
            OAUTH_CALLBACK_URL: http://api.localhost
            OAUTH_YANDEX_AUTH_URL: http://wiremock.localhost/oauth.yandex.ru
            OAUTH_YANDEX_TOKEN_URL: http://wiremock:8080/oauth.yandex.ru
            OAUTH_YANDEX_API_URL: http://wiremock:8080/login.yandex.ru
            OAUTH_YANDEX_CLIENT_ID: app
            OAUTH_YANDEX_CLIENT_SECRET: yandex-secret
            OAUTH_MAILRU_AUTH_URL: http://wiremock.localhost/oauth.mail.ru
            OAUTH_MAILRU_TOKEN_URL: http://wiremock:8080/oauth.mail.ru
            OAUTH_MAILRU_API_URL: http://wiremock:8080/oauth.mail.ru
            OAUTH_MAILRU_CLIENT_ID: app
            OAUTH_MAILRU_CLIENT_SECRET: mailru-secret
        volumes:
            - ./api:/app
        secrets:
            - jwt_public_key
            - jwt_private_key

    api-php-cli:
        build:
            context: api/docker
            dockerfile: development/php-cli/Dockerfile
            args:
                GID: ${GID:-1000}
                UID: ${UID:-1000}
        environment:
            APP_ENV: dev
            APP_DEBUG: 1
            DB_HOST: api-postgres
            DB_USER: app
            DB_PASSWORD: secret
            DB_NAME: app
            MAILER_HOST: mailer
            MAILER_PORT: 1025
            MAILER_USERNAME: app
            MAILER_PASSWORD: secret
            MAILER_FROM_EMAIL: mail@app.test
            FRONTEND_URL: http://localhost
            SENTRY_DSN: ""
            JWT_ENCRYPTION_KEY: secret
            JWT_PUBLIC_KEY_PATH: /run/secrets/jwt_public_key
            JWT_PRIVATE_KEY_PATH: /run/secrets/jwt_private_key
            OAUTH_CALLBACK_URL: http://api.localhost
            OAUTH_YANDEX_AUTH_URL: http://wiremock.localhost/oauth.yandex.ru
            OAUTH_YANDEX_TOKEN_URL: http://wiremock:8080/oauth.yandex.ru
            OAUTH_YANDEX_API_URL: http://wiremock:8080/login.yandex.ru
            OAUTH_YANDEX_CLIENT_ID: app
            OAUTH_YANDEX_CLIENT_SECRET: yandex-secret
            OAUTH_MAILRU_AUTH_URL: http://wiremock.localhost/oauth.mail.ru
            OAUTH_MAILRU_TOKEN_URL: http://wiremock:8080/oauth.mail.ru
            OAUTH_MAILRU_API_URL: http://wiremock:8080/oauth.mail.ru
            OAUTH_MAILRU_CLIENT_ID: app
            OAUTH_MAILRU_CLIENT_SECRET: mailru-secret
        volumes:
            - ./api:/app
        secrets:
            - jwt_public_key
            - jwt_private_key

    api-postgres:
        image: postgres:17.7-alpine3.23
        environment:
            POSTGRES_USER: app
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: app
        volumes:
            - api-postgres:/var/lib/postgresql/data
        ports:
            - "5432:5432"

    api-postgres-backup:
        build:
            context: ./api/docker/common
            dockerfile: postgres-backup/Dockerfile
        environment:
            BACKUP_NAME: auction_api-postgres
            POSTGRES_HOST: api-postgres
            POSTGRES_DB: app
            POSTGRES_USERNAME: app
            POSTGRES_PASSWORD: secret
            AWS_ACCESS_KEY_ID: storage_app
            AWS_SECRET_ACCESS_KEY: storage_secret
            AWS_DEFAULT_REGION: region
            S3_ENDPOINT: http://backup-storage:9090
            S3_BUCKET: backup
        volumes:
            - api-postgres-backup:/app
        command: ["sh", "-c", "wait-for-it api-postgres:5432 -t 20 && exec backup"]

    mailer:
        image: axllent/mailpit:v1.27
        environment:
            MP_SMTP_AUTH_ACCEPT_ANY: 1
            MP_SMTP_AUTH_ALLOW_INSECURE: 1
        networks:
            - traefik-public
            - default
        labels:
            - traefik.enable=true
            - traefik.docker.network=traefik-public
            - traefik.http.routers.mailer.rule=Host(`mailer.localhost`)
            - traefik.http.routers.mailer.entryPoints=http
            - traefik.http.services.mailer.loadBalancer.server.port=8025

    wiremock:
        image: wiremock/wiremock:3x-alpine
        networks:
            - traefik-public
            - default
        volumes:
            - ./wiremock:/home/wiremock
        command:
            - '--global-response-templating'
            - '--verbose'
        labels:
            - traefik.enable=true
            - traefik.docker.network=traefik-public
            - traefik.http.routers.wiremock.rule=Host(`wiremock.localhost`)
            - traefik.http.services.wiremock.loadBalancer.server.port=8080
            - traefik.http.routers.wiremock.entryPoints=http

    backup-storage:
        image: adobe/s3mock:4.11.0
        environment:
            initialBuckets: backup
            root: data
        volumes:
            - backup-storage:/data
        networks:
            - traefik-public
            - default
        labels:
            - traefik.enable=true
            - traefik.docker.network=traefik-public
            - traefik.http.routers.backup-storage.rule=Host(`backup-storage.localhost`)
            - traefik.http.routers.backup-storage.entryPoints=http
            - traefik.http.services.backup-storage.loadBalancer.server.port=9090

    cucumber-node-cli:
        build:
            context: cucumber/docker/development/node
            args:
                GID: ${GID:-1000}
                UID: ${UID:-1000}
        volumes:
            - ./cucumber:/app
        network_mode: service:traefik

secrets:
    jwt_public_key:
        file: ./docker/development/secrets/jwt_public_key
    jwt_private_key:
        file: ./docker/development/secrets/jwt_private_key

volumes:
    api-postgres:
    api-postgres-backup:
    backup-storage:

networks:
    traefik-public:
        name: traefik-public
